pipelines:
  default:
    - parallel:
        - step:
            image: python:latest
            script:
              - python -m unittest discover aniso8601
        - step:
            image: python:3.9
            script:
              - python -m unittest discover aniso8601
        - step:
            image: python:3.8
            script:
              - python -m unittest discover aniso8601
        - step:
            image: python:3.7
            script:
              - python -m unittest discover aniso8601
        - step:
            image: python:3.6
            script:
              - python -m unittest discover aniso8601
        - step:
            image: python:3.5
            script:
              - python -m unittest discover aniso8601
        - step:
            image: python:3.4
            script:
              - python -m unittest discover aniso8601
        - step:
            image: python:2.7
            script:
              - pip install mock
              - python -m unittest discover aniso8601
