pipelines:
  default:
    - parallel:
        - step:
            image: python:latest
            script:
              - pip install .[relative]
              - python setup.py test
        - step:
            image: python:3.7
            script:
              - pip install .[relative]
              - python setup.py test
        - step:
            image: python:3.6
            script:
              - pip install .[relative]
              - python setup.py test
        - step:
            image: python:3.5
            script:
              - pip install .[relative]
              - python setup.py test
        - step:
            image: python:3.4
            script:
              - pip install .[relative]
              - python setup.py test
        - step:
            image: python:2.7
            script:
              - pip install .[relative]
              - python setup.py test
